id: A2C692925
title: Prayer for the Long Life of Khyenrab Chökyi Özer
type: translation
pechas:
- IA3D1A414
- IFDA34398
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:55:51.215425
  last_modified_at: 2023-01-04 12:55:51.215444
  collections:
  - Khyenrab Chökyi Özer Series
  - Works of Tibetan Masters
alignment_to_base:
  IA3D1A414/B2A3: '6663'
  IFDA34398/EEE7: '6663'
